<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L2CategoryInFlyout_HP</name>
   <tag></tag>
   <elementGuidId>59073cec-a5db-48fb-a859-c1bfa1e59e9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@data-submenu-id='CAT610036']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-desktop__categoryTitle.categoryLevel-2undefined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f664cc01-6662-49eb-afac-e63db19b2516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-desktop__categoryTitle categoryLevel-2undefined</value>
      <webElementGuid>9d007be8-6fa6-4e27-ae4f-bc490995513c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ropa</value>
      <webElementGuid>ae2362ee-2e08-4a1f-af8a-f820878ccb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CAT610036&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-top&quot;]/div[@class=&quot;col-lg-8 category-menu&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 pb-3&quot;]/a[@class=&quot;a-desktop__categoryTitle categoryLevel-2undefined&quot;]</value>
      <webElementGuid>7ba22f85-9937-48bc-b596-f29d3055f228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CAT610036']/div/div[2]/div/div/div/a</value>
      <webElementGuid>a14bf7ee-1139-4c6a-bd12-b67cc0b13776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ropa')]</value>
      <webElementGuid>15708cd9-d43a-4e3a-bb15-d4d14512fa07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[2]/following::a[1]</value>
      <webElementGuid>4712a4ab-d202-4eb2-95d7-9015f268215e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ella'])[1]/following::a[2]</value>
      <webElementGuid>41d128b7-b8cc-4b3f-9b3b-8060a1a2f22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chamarras Abrigos &amp; Chalecos'])[1]/preceding::a[1]</value>
      <webElementGuid>977f4292-f908-443d-9c48-28fc7992c149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suéteres &amp; Sudaderas'])[1]/preceding::a[2]</value>
      <webElementGuid>76078cf4-121b-43df-8fc9-1e967d866241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ropa']/parent::*</value>
      <webElementGuid>e47bc923-7e84-4f66-b9f9-5f49f64ad486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>b30af114-15b1-4ea4-ba91-f81b5f8f51ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Ropa' or . = 'Ropa')]</value>
      <webElementGuid>199bea91-0495-4558-ba5c-2c4d940fd30a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
