<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Color_variants-normalizedColor-Blanco_plp</name>
   <tag></tag>
   <elementGuidId>242f756f-9d29-4fca-aad1-f3b1128fb2f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#variants-normalizedColor-Blanco</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class='a-plp-color']//li[@class='a-productColor__item a-product__color'][2])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4d26599-fdc8-4af2-ac37-4445ccb93652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-productColor__item a-product__color atom-color</value>
      <webElementGuid>edccd939-f302-492c-9011-87e636b529f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>variants-normalizedColor-Blanco</value>
      <webElementGuid>7d386249-187b-4893-a7d5-39573277de4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-color</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>6165a373-6a39-431d-b67c-91fb6f481dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variants-normalizedColor-Blanco&quot;)</value>
      <webElementGuid>b6d623d1-4e59-4484-a081-539e9738beed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='variants-normalizedColor-Blanco']</value>
      <webElementGuid>2e3f5d75-797e-4d0d-8a9c-46deccffca25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[4]/aside/div/div/div[26]/div[2]/ul/li/a</value>
      <webElementGuid>f901cbf1-44f1-4f10-9f80-8cfdb3424ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div[2]/ul/li/a</value>
      <webElementGuid>7ae2f48b-e703-4f1d-8467-073f9797f169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'variants-normalizedColor-Blanco']</value>
      <webElementGuid>5b72032f-27b6-4c3c-9d04-443877b27baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
